[tox]
requires = tox>=4
env_list = py312, py313
isolated_build = true

[testenv]
extras = test
commands =
    pytest {posargs}
    ytt --help
    ytt --version
    python -c "import os, pathlib, tempfile; from importlib import metadata; os.chdir(tempfile.mkdtemp()); import ytt, ytt.domain; path = pathlib.Path(ytt.__file__).resolve(); print(path); assert 'site-packages' in str(path); assert metadata.version('ytt') == ytt.__version__"
